version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: cc_payoff_dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
